#! /bin/zsh

if (( # == 0 )); then
  print >&2 "Usage: $0 nubank"
  exit 1
fi

values=

case "$1" in
  "nubank")
    nix build .#homeManagerConfigurations.zoedsoupe.activationPackage
    ./result/activate
    ;;

  "iso")
    nix build .#installMedia..config.system.build.isoImage
    ;;

  *)
    print >&2 "Available options are \"nubank\" and \"iso\" for now"
    exit 1
    ;;
esac
