#! /bin/zsh

if (( # == 0 )); then
  print >&2 "Usage: $0 nubank"
  exit 1
fi

case "$1" in
  "nubank")
    nix build .#darwinConfigurations.nubank.system
    sudo ./result/activate
    ;;

  "personal")
     nix build .#darwinConfigurations.zoedsoupe.system
     sudo ./result/activate
     ;;

  "iso")
    nix build .#installMedia..config.system.build.isoImage
    ;;

  *)
    print >&2 "Available options are \"nubank\", \"personal\" \"iso\" for now"
    exit 1
    ;;
esac
