#! /bin/zsh

if (( # == 0 )); then
  print >&2 "Usage: $0 personal or iso"
  exit 1
fi

case "$1" in
  "personal")
     if ! type darwin-rebuild > /dev/null; then
       nix run nix-darwin -- switch --flake .
     else
       darwin-rebuild switch --flake .
     fi
     ;;

  "iso")
    nix build .#installMedia.minimal.config.system.build.isoImage "${@:2}"
    ;;

  *)
    print >&2 "Available options are, \"personal\" \"iso\" for now"
    exit 1
    ;;
esac
