# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    cryptKey = {
      device = "/dev/disk/by-uuid/ab2eca07-9378-4ee0-97a8-98e6d4f75c64";
      allowDiscards = true;
    };
    cryptswap = {
      device = "/dev/disk/by-uuid/971c0496-7d77-4ccf-a9be-33ae2105c9d3";
      keyFileSize = 8192;
    };
    cryptroot = {
      device = "/dev/disk/by-uuid/a8a2c0e4-a65c-447f-b2b5-40e18d8b52e9";
      keyFileSize = 8192;
    };
  };

  fileSystems."/" =
    { device = "cumbuca-pool/system/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5902-4E51";
      fsType = "vfat";
    };

  fileSystems."/var" =
    { device = "cumbuca-pool/system/var";
      fsType = "zfs";
    };

  fileSystems."/home/zoedsoupe" =
    { device = "cumbuca-pool/user/home/zoedsoupe";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "cumbuca-pool/local/nix";
      fsType = "zfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp43s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
